### ISSUE TITLE
CFLAGS/CXXFLAGS in environment are not used

### ISSUE THREAD

**Issue by scop** [aperezdc/nss-altfiles#2]
configure documents use of CFLAGS/CXXFLAGS in environment and grabs them to corresponding EXTRA_* variables but actually does nothing to them. It does write CFLAGS/CXXFLAGS from configure *arguments* to config.mk but that's different from the env vars.

**Comment by aperezdc** [comment]
In my experience the most usual (and useful) behaviour is that the `configure` script picks the environment variables, without being it so important that the `Makefile` honors the values they have later on. In which use case would you want to one value of `CFLAGS`/`CXXFLAGS` for `configure` step and different values for the build step?

**Comment by scop** [comment]
That's not what I'm looking for at all. I'm trying to point out an obvious bug where the CFLAGS/CXXFLAGS set in **environment** for the configure script have no effect at all, despite what the configure usage message and usual configure behavior says. The CFLAGS/CXXFLAGS settings only work when given as **arguments** to configure.

Here's a test: with those flags given as arguments it does work:
```shell
$ make distclean >/dev/null
$ ./configure CFLAGS=-DJUST_FOR_TESTING >/dev/null
$ grep EXTRA_CFLAGS config.mk
EXTRA_CFLAGS=-DJUST_FOR_TESTING
```
...and with env vars it does not work:
```shell
$ make distclean >/dev/null
$ CFLAGS=-DJUST_FOR_TESTING ./configure >/dev/null
$ grep EXTRA_CFLAGS config.mk
# no output, CFLAGS in environment was ignored
```

PR #7 which I just submitted contains one way to fix this.

**Comment by aperezdc** [comment]
@scop: Oh, I misunderstood your original bug issue report, sorry! Thanks a lot for the clarification — you are absolutely right.
