### ISSUE TITLE
Querying given data-dir parameter in runtime

### ISSUE THREAD

**Issue by c4milo** [aperezdc/nss-altfiles#4]
Is there anyway to know what was the data-dir parameter passed during compilation? it would be very useful to have it around somewhere, especially for tooling in other programming languages trying to do user lookups without linking with C libraries.

**Comment by aperezdc** [comment]
There is no direct way. An idea could be to add a small tool which allows querying the build configuration.

**Comment by aperezdc** [comment]
I have just pushed a commit to `master` which works as follows:
```
% ./nss-altfiles-config datadir
/etc/alt
% ./nss-altfiles-config modulename
altfiles
```

This should be enough for scripting e.g. using a shell.

**Comment by c4milo** [comment]
Nice! Thanks @aperezdc for addressing this so quickly.
